In [1]:
import pandas as pd
import numpy as np
dt=pd.read_csv(r'C:\Users\DELL\Downloads\Iris.csv')

In [2]:
dt

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [3]:
x=dt.iloc[:,1:5].values

In [4]:
y=dt.iloc[:,5].values

In [5]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [6]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

***LOGISTIC REGRESSION***

In [10]:
from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)


C:\Users\DELL\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [11]:
y_pred=logmodel.predict(x_test)
y_pred

array([0, 1, 1, 0, 0, 2, 2, 0, 1, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 1, 2, 0,
       1, 1, 2, 0, 1, 1, 2, 0])

In [12]:
y_test

array([0, 1, 1, 0, 0, 2, 2, 0, 1, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 1, 1, 0,
       1, 1, 2, 0, 1, 1, 2, 0])

In [13]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)


array([[15,  0,  0],
       [ 0,  8,  1],
       [ 0,  0,  6]], dtype=int64)

In [14]:
from sklearn.metrics import accuracy_score
a=accuracy_score(y_test,y_pred)*100
print("Your model's Accuracy is : ",a,"%")


Your model's Accuracy is :  96.66666666666667 %


***KNN***

In [29]:
from sklearn.neighbors import KNeighborsClassifier


In [30]:
classifier_KNN=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier_KNN.fit(x_train,y_train)

KNeighborsClassifier()

In [31]:
y_pred=classifier_KNN.predict(x_test)


In [32]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[15,  0,  0],
       [ 0,  7,  2],
       [ 0,  0,  6]], dtype=int64)

In [33]:
from sklearn.metrics import accuracy_score
a=accuracy_score(y_test,y_pred)*100
print("Your model's Accuracy is : ",a,"%")

Your model's Accuracy is :  93.33333333333333 %


***NAIVE BAYES***

...............

In [22]:
from sklearn.svm import SVC

In [34]:
s=SVC(kernel='sigmoid')
s.fit(x_train,y_train)


SVC(kernel='sigmoid')

In [35]:
y_pred=s.predict(x_test)
confusion_matrix(y_test,y_pred)

array([[ 0,  0, 15],
       [ 0,  0,  9],
       [ 0,  0,  6]], dtype=int64)

In [36]:
from sklearn.metrics import accuracy_score
a=accuracy_score(y_test,y_pred)*100
print("Your model's Accuracy is : ",a,"%")

Your model's Accuracy is :  20.0 %


In [38]:
s=SVC(kernel='rbf')
s.fit(x_train,y_train)


SVC()

In [39]:
y_pred=s.predict(x_test)
confusion_matrix(y_test,y_pred)

array([[15,  0,  0],
       [ 0,  7,  2],
       [ 0,  0,  6]], dtype=int64)

In [40]:
from sklearn.metrics import accuracy_score
a=accuracy_score(y_test,y_pred)*100
print("Your model's Accuracy is : ",a,"%")

Your model's Accuracy is :  93.33333333333333 %
